/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	servingv1 "knative.dev/serving/pkg/apis/serving/v1"
)

// FakeFuncPools implements FuncPoolInterface
type FakeFuncPools struct {
	Fake *FakeServingV1
	ns   string
}

var funcpoolsResource = schema.GroupVersionResource{Group: "serving.knative.dev", Version: "v1", Resource: "funcpools"}

var funcpoolsKind = schema.GroupVersionKind{Group: "serving.knative.dev", Version: "v1", Kind: "FuncPool"}

// Get takes name of the funcPool, and returns the corresponding funcPool object, and an error if there is any.
func (c *FakeFuncPools) Get(name string, options v1.GetOptions) (result *servingv1.FuncPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(funcpoolsResource, c.ns, name), &servingv1.FuncPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*servingv1.FuncPool), err
}

// List takes label and field selectors, and returns the list of FuncPools that match those selectors.
func (c *FakeFuncPools) List(opts v1.ListOptions) (result *servingv1.FuncPoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(funcpoolsResource, funcpoolsKind, c.ns, opts), &servingv1.FuncPoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &servingv1.FuncPoolList{ListMeta: obj.(*servingv1.FuncPoolList).ListMeta}
	for _, item := range obj.(*servingv1.FuncPoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested funcPools.
func (c *FakeFuncPools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(funcpoolsResource, c.ns, opts))

}

// Create takes the representation of a funcPool and creates it.  Returns the server's representation of the funcPool, and an error, if there is any.
func (c *FakeFuncPools) Create(funcPool *servingv1.FuncPool) (result *servingv1.FuncPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(funcpoolsResource, c.ns, funcPool), &servingv1.FuncPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*servingv1.FuncPool), err
}

// Update takes the representation of a funcPool and updates it. Returns the server's representation of the funcPool, and an error, if there is any.
func (c *FakeFuncPools) Update(funcPool *servingv1.FuncPool) (result *servingv1.FuncPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(funcpoolsResource, c.ns, funcPool), &servingv1.FuncPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*servingv1.FuncPool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFuncPools) UpdateStatus(funcPool *servingv1.FuncPool) (*servingv1.FuncPool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(funcpoolsResource, "status", c.ns, funcPool), &servingv1.FuncPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*servingv1.FuncPool), err
}

// Delete takes name of the funcPool and deletes it. Returns an error if one occurs.
func (c *FakeFuncPools) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(funcpoolsResource, c.ns, name), &servingv1.FuncPool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFuncPools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(funcpoolsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &servingv1.FuncPoolList{})
	return err
}

// Patch applies the patch and returns the patched funcPool.
func (c *FakeFuncPools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *servingv1.FuncPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(funcpoolsResource, c.ns, name, pt, data, subresources...), &servingv1.FuncPool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*servingv1.FuncPool), err
}
